-- Supabase schema for folder-based person counting service

create table if not exists public.camera_staffing_targets (
  camera_id text primary key,
  required_count integer not null check (required_count >= 0),
  is_active boolean not null default true,
  location_name text,
  updated_at timestamptz not null default now()
);

create table if not exists public.person_count_results (
  id bigint generated by default as identity primary key,
  processed_at timestamptz not null,
  camera_id text not null,
  source_file_name text not null,
  source_file_path text not null,
  archived_file_path text not null,
  person_count integer not null check (person_count >= 0),
  required_count integer not null check (required_count >= 0),
  status text not null, -- 'SHORTAGE' (Thiếu), 'SUFFICIENT' (Đủ), 'SURPLUS' (Thừa)
  created_at timestamptz not null default now()
);

create index if not exists idx_person_count_results_camera_time
  on public.person_count_results (camera_id, processed_at desc);

create table if not exists public.staffing_alerts (
  id bigint generated by default as identity primary key,
  result_id bigint not null references public.person_count_results(id) on delete cascade,
  created_at timestamptz not null default now(),
  camera_id text not null,
  source_file_name text not null,
  person_count integer not null check (person_count >= 0),
  required_count integer not null check (required_count >= 0),
  status text not null default 'OPEN'
);

create index if not exists idx_staffing_alerts_camera_time
  on public.staffing_alerts (camera_id, created_at desc);

-- Example seed data
insert into public.camera_staffing_targets (camera_id, required_count, is_active, location_name)
values
  ('camera-a', 3, true, 'Office A'),
  ('camera-b', 5, true, 'Office B')
on conflict (camera_id) do update
set
  required_count = excluded.required_count,
  is_active = excluded.is_active,
  location_name = excluded.location_name,
  updated_at = now();
